CREATE TABLE IF NOT EXISTS map (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    data BLOB NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);